service: ratecalculationengineservice

provider:
  name: aws
  runtime: dotnetcore2.1
  region: ap-southeast-2
  profile: demo-admin

package:
  artifact: bin/release/netcoreapp2.1/deploy-package.zip

functions:
  api:
    handler: RateCalculationEngine::RateCalculationEngine.LambdaEntryPoint::FunctionHandlerAsync
    events:
     - http:
         path: /{proxy+}
         method: ANY